### ISSUE TITLE
Clair3 fails to parse region

### ISSUE THREAD

**Issue by Eric-Altermann** [OLF-Bioinformatics/VariantDetective#11]
Hi,
I installed Variant Detective to work on bacterial genomes and found that Claire3 is not working - even with the test dataset.
Any idea what causes this behavior.
I have copied the log below for the test dataset.
Cheers
Eric

[INFO] CLAIR3 VERSION: v0.1-r11
[INFO] BAM FILE PATH: /home/eric/VariantDetective/testdata/test/snp_indel/alignment.rg.sorted.bam
[INFO] REFERENCE FILE PATH: /home/eric/VariantDetective/testdata/test/testdata_ref.fasta
[INFO] MODEL PATH: /home/eric/anaconda3/envs/variantdetective/bin/models/ilmn
[INFO] OUTPUT FOLDER: /home/eric/VariantDetective/testdata/test/snp_indel/clair3
[INFO] PLATFORM: ilmn
[INFO] THREADS: 1
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /home/eric/anaconda3/envs/variantdetective
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.3
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.3
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.08
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: True
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: True
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: True
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE LONGPHASE_FOR_PHASING: False
[INFO] ENABLE C_IMPLEMENT: True

[33m[WARNING] Illumina platform will disable C implement to support short read realignment process! [0m
+ /home/eric/anaconda3/envs/variantdetective/bin/scripts/clair3.sh --bam_fn /home/eric/VariantDetective/testdata/test/snp_indel/alignment.rg.sorted.bam --ref_fn /home/eric/VariantDetective/testdata/test/testdata_ref.fasta --threads 1 --model_path /home/eric/anaconda3/envs/variantdetective/bin/models/ilmn --platform ilmn --output /home/eric/VariantDetective/testdata/test/snp_indel/clair3 --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.3 --ref_pct_full=0.3 --var_pct_phasing=0.7 --snp_min_af=0.08 --indel_min_af=0.08 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=False --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=True --haploid_sensitive=False --include_all_ctgs=True --no_phasing_for_fa=True --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=False --enable_long_indel=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY

[INFO] Check environment variables
[INFO] --include_all_ctgs enabled
[93m[WARNING] Please enable --no_phasing_for_fa if calling variant in non-diploid organisms[0m
[INFO] Call variant in contigs: testdata_ref
[INFO] Chunk number for each contig: 1
[93m[WARNING] Current maximum contig length 100000 is much smaller than default chunk size 5000000, You may set a smaller chunk size by setting --chunk_size=$ for better parallelism.[0m
[INFO] 1/7 Call variants using pileup model
[INFO] Delay 1 seconds before starting variant calling ...
[faidx] Truncated sequence: testdata_ref:1-101000
[E::hts_parse_region] Coordinates must be > 0
[E::mpileup] fail to parse region 'testdata_ref:-33-100033' with /home/eric/VariantDetective/testdata/test/snp_indel/alignment.rg.sorted.bam
Calling variants ...
Total processed positions in testdata_ref (chunk 1/1) : 0
Total time elapsed: 0.00 s
[INFO] No vcf output for file /home/eric/VariantDetective/testdata/test/snp_indel/clair3/tmp/pileup_output/pileup_testdata_ref_1.vcf, remove empty file

real	0m2.384s
user	0m1.338s
sys	0m0.157s
[93m[WARNING] No vcf file found with prefix:/home/eric/VariantDetective/testdata/test/snp_indel/clair3/tmp/pileup_output/pileup, output empty vcf file[0m
[93m[WARNING] Copying pileup.vcf.gz to /home/eric/VariantDetective/testdata/test/snp_indel/clair3/merge_output.vcf.gz[0m
[INFO] Exit in pileup variant calling

real	0m3.187s
user	0m1.964s
sys	0m0.255s

**Comment by philcharron-cfia** [comment]
Hey @Eric-Altermann,

Thanks for trying out our tool. Unfortunately, I'm not able to replicate your error when following the steps on the repo.

- I performed a fresh install with these steps: https://github.com/OLF-Bioinformatics/VariantDetective?tab=readme-ov-file#installation-from-source

- I then ran the test data using these steps: https://github.com/OLF-Bioinformatics/VariantDetective?tab=readme-ov-file#test-data

There were no issues when running the test data using this method.

What isn't working specifically?

**Comment by Eric-Altermann** [comment]
Hi Phil, 
thanks for checking. I have done a new install via conda and tried again using the provided test data.
With the snp_indel option, I am getting the same error message for Claire 3 as shown above with this seeming to be the main problem "fail to parse region 'testdata_ref:-33-100033' with /home/eric/VariantDetective/testdata/test/snp_indel/alignment.rg.sorted.bam".

I also ran the default all_variants test and this breaks while running NanoSV with the below error output:
(vd2) eric@eric-x570aoruselitewifi:~/VD.test$ variantdetective all_variants -r testdata/testdata_ref.fasta -g testdata/testdata_mut.fasta -o testdata/test
2024-05-20 15:34:11     Starting genome pipeline
2024-05-20 15:34:11     Simulating long-reads from genomic sequence...
2024-05-20 15:34:11     Starting structural_variant tool
2024-05-20 15:34:11     Running NanoVar...
2024-05-20 15:34:20     Sorting BAM file...
2024-05-20 15:34:20     Indexing sorted BAM file...                                                                                                                                        
2024-05-20 15:34:20     Running NanoSV...                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                         
  File "/home/eric/anaconda3/envs/vd2/bin/variantdetective", line 10, in <module>                                                                                                          
    sys.exit(main())                                                                                                                                                                       
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/main.py", line 39, in main                                                                              
    validate_inputs(args, output=output)                                                                                                                                                   
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/validate_inputs.py", line 64, in validate_inputs                                                        
    long_bam_file = structural_variant(args, sim_file, output=sys.stderr)                                                                                                                  
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/structural_variant.py", line 81, in structural_variant                                                  
    run_process(command)                                                                                                                                                                   
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/tools.py", line 77, in run_process                                                                      
    raise Exception(error)                                                                                                                                                                 
Exception: Mon May 20 15:34:21 2024 Busy with calculating the coverage distribution...                                                                                                     
Mon May 20 15:34:23 2024 Busy with parsing bam file...                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                         
  File "/home/eric/anaconda3/envs/vd2/bin/NanoSV", line 10, in <module>                                                                                                                    
    sys.exit(main())                                                                                                                                                                       
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/NanoSV.py", line 73, in main                                                                                      
    utils.create_vcf.print_vcf_header()                                                                                                                                                    
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/utils/../utils/create_vcf.py", line 25, in print_vcf_header                                                       
    set_info_header(vcf)                                                                                                                                                                   
  File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/utils/../utils/create_vcf.py", line 59, in set_info_header                                                        
    'IMPRECISE': py_vcf.parser._Info("IMPRECISE", 0, "Flag", "Imprecise structural variant", "NanoSV", __version__),                                                                       
TypeError: __new__() missing 1 required positional argument: 'type_code'

**Comment by arunprasanna83** [comment]
> Hi Phil, thanks for checking. I have done a new install via conda and tried again using the provided test data. With the snp_indel option, I am getting the same error message for Claire 3 as shown above with this seeming to be the main problem "fail to parse region 'testdata_ref:-33-100033' with /home/eric/VariantDetective/testdata/test/snp_indel/alignment.rg.sorted.bam".
> 
> I also ran the default all_variants test and this breaks while running NanoSV with the below error output: (vd2) eric@eric-x570aoruselitewifi:~/VD.test$ variantdetective all_variants -r testdata/testdata_ref.fasta -g testdata/testdata_mut.fasta -o testdata/test 2024-05-20 15:34:11 Starting genome pipeline 2024-05-20 15:34:11 Simulating long-reads from genomic sequence... 2024-05-20 15:34:11 Starting structural_variant tool 2024-05-20 15:34:11 Running NanoVar... 2024-05-20 15:34:20 Sorting BAM file... 2024-05-20 15:34:20 Indexing sorted BAM file... 2024-05-20 15:34:20 Running NanoSV... Traceback (most recent call last): File "/home/eric/anaconda3/envs/vd2/bin/variantdetective", line 10, in sys.exit(main()) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/main.py", line 39, in main validate_inputs(args, output=output) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/validate_inputs.py", line 64, in validate_inputs long_bam_file = structural_variant(args, sim_file, output=sys.stderr) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/structural_variant.py", line 81, in structural_variant run_process(command) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/variantdetective/tools.py", line 77, in run_process raise Exception(error) Exception: Mon May 20 15:34:21 2024 Busy with calculating the coverage distribution... Mon May 20 15:34:23 2024 Busy with parsing bam file... Traceback (most recent call last): File "/home/eric/anaconda3/envs/vd2/bin/NanoSV", line 10, in sys.exit(main()) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/NanoSV.py", line 73, in main utils.create_vcf.print_vcf_header() File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/utils/../utils/create_vcf.py", line 25, in print_vcf_header set_info_header(vcf) File "/home/eric/anaconda3/envs/vd2/lib/python3.6/site-packages/nanosv/utils/../utils/create_vcf.py", line 59, in set_info_header 'IMPRECISE': py_vcf.parser._Info("IMPRECISE", 0, "Flag", "Imprecise structural variant", "NanoSV", **version**), TypeError: **new**() missing 1 required positional argument: 'type_code'

Yes. Getting the same error 

  ```
File "/ibex/project/c2198/ARUN/Softwares/conda/miniforge3/envs/vd/lib/python3.6/site-packages/nanosv/utils/../utils/create_vcf.py", line 59, in set_info_header
    'IMPRECISE': py_vcf.parser._Info("IMPRECISE", 0, "Flag", "Imprecise structural variant", "NanoSV", __version__),
TypeError: __new__() missing 1 required positional argument: 'type_code'
```

**Comment by th-of** [comment]
Conda installation does not work for me (same error as above: TypeError: new() missing 1 required positional argument: 'type_code'), but the installation from source works.
