### ISSUE TITLE
Implement a check for an output directory that already exists with results

### ISSUE THREAD

**Issue by pcrxn** [OLF-Bioinformatics/VariantDetective#9]
When attempting to use `-o` with an output directory that already contains VariantDetective results from another run, an error isn't immediately raised:

```
$ variantdetective snp_indel -t 12 \
    -r data/assembly/fasta/E4166S_0.assembly.fasta \
    -1 data/raw/illumina/fastq_gz/BMH-2022-000218_R1.fastq.gz \
    -2 data/raw/illumina/fastq_gz/BMH-2022-000218_R2.fastq.gz \
    -o variantdetective/raw/E4166S-0_E4166-0
2024-02-28 14:45:44     Starting short read pipeline
2024-02-28 14:45:44     Starting snp_indel tool
2024-02-28 14:45:44     Running bwa...
Traceback (most recent call last):
  File "/home/liam/miniconda3/envs/variantdetective/bin/variantdetective", line 33, in <module>
    sys.exit(load_entry_point('variantdetective', 'console_scripts', 'variantdetective')())
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/VariantDetective/variantdetective/main.py", line 39, in main
    validate_inputs(args, output=output)    
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/VariantDetective/variantdetective/validate_inputs.py", line 77, in validate_inputs
    snp_indel(args, short_inputs, output=sys.stderr)
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/VariantDetective/variantdetective/snp_indel.py", line 70, in snp_indel
    run_process(command)
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/VariantDetective/variantdetective/tools.py", line 77, in run_process
    raise Exception(error)
Exception: INFO 2024-02-28 14:46:39     CreateSequenceDictionary

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** 
https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CreateSequenceDictionary -R variantdetective/raw/E4166S-0_E4166-0/E4166S_0.assembly.fasta
**********


INFO    2024-02-28 14:46:39     CreateSequenceDictionary        Output dictionary will be written in variantdetective/raw/E4166S-0_E4166-0/E4166S_0.assembly.dict
14:46:39.448 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/liam/miniconda3/envs/variantdetective/share/picard-2.27.3-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Feb 28 14:46:39 EST 2024] CreateSequenceDictionary REFERENCE=variantdetective/raw/E4166S-0_E4166-0/E4166S_0.assembly.fasta    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Feb 28 14:46:39 EST 2024] Executing as liam@liam-Legion-T7-34IAZ7 on Linux 5.15.0-88-generic amd64; OpenJDK 64-Bit Server VM 11.0.8-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.27.3
[Wed Feb 28 14:46:39 EST 2024] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=536870912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: /media/liam/Cerulean/projects/PRJ-LPB-00017/variantdetective/raw/E4166S-0_E4166-0/E4166S_0.assembly.dict already exists.  Delete this file and try again, or specify a different output file.
        at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:220)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

I'd recommend performing a check initially within the `-o` directory to see if any VariantDetective results already exist, so that no intermediate files are written in the existing `-o` directory.

**Comment by philcharron-cfia** [comment]
Based off the referenced commit (1a40dbc945515668806bda75affd83644e3b9346), files found within a output directory that already exists will be overwritten if using the same sample name and reference.
